const products = [
  {
    brand: "Gibson",
    model: "Billie Joe Armstrong Les Paul Junior",
    slug: "billie-joe-armstrong-les-paul-junior",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/6h4ogHG5nxTLIEbbpY1hzy/85555a4911b1504d5c3575740799b3a8/LPJRBA22S1NH1_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/52LN0tVh4sQivTzzW4aDC0/f2e2d58462b0d6e5122ffb0c35d630c8/LPJRBA22S1NH1_side.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/3l4dOSNF6acZotFszSJV2F/ea443c0426e122864c924ac519cd23e2/LPJRBA22S1NH1_beauty.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/NXtIFXoEZ9JWgv3pnwuro/8094f56ba4fdc6a72e88389358281b2d/LPJRBA22S1NH1_hs.png?h=1080",
    ],
    highlight: false,
    price: 2199,
    stock: 10,
    category: "Electric",
    subtitle: "Designed by the Green Day Punk Rock Legend",
    description:
      "The new Billie Joe Armstrong Les Paul™ Junior is an exceptional guitar to rock out on, whether you play rock or punk. Designed in collaboration with Green Day’s legendary guitarist, it has everything you need for great tone with no frills to get in your way, including a mahogany neck with a Billie Joe Armstrong SlimTaper™ profile, rosewood fretboard, Graph Tech® nut, and Billie Joe’s signature on the truss rod cover. The mahogany body is equipped with a wraparound bridge/tailpiece and a P-90 DC Dogear pickup. The P-90 DC is our latest hum-canceling design. It features a modernized version of the Sidewinder dual-coil technology that was first developed by Seth Lover in 1958, delivering a hum-free P-90 with the most authentic P-90 tonality yet, retaining the classic sound of a single",
    detail: {
      bodyStyle: "Les Paul",
      bodyShape: "Les Paul Junior",
      bodyMaterial: "Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "B.B. King Live at the Regal ES-335",
    slug: "bb-king-live-at-the-regal-es-335",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/3djWs8U7hFdy2TeDVWS4Cu/762d54683ad54e44aae82c988529cfbe/BBES335REAGNB1_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/O2zMaCOUsZOkobeTppUqK/81fc86c9d3dc4a70f44381d444a4ea01/BBES335REAGNB1_side.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/3RXyrwWZrAdW89cKA0Jt5P/0166c2754c8415a257a7634ac40e8115/BBES335REAGNB1_pups.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/17rjBaf7yIK9QvPr9pdATJ/74c1d331c951e5bac332bc8bd0661817/BBES335REAGNB1_hs.png?h=1080",
    ],
    highlight: true,
    price: 9999,
    stock: 3,
    category: "Electric",
    subtitle:
      "A Faithful Tribute to a Live Music Icon and a Legendary Guitarist",
    description:
      "Gibson Custom Shop is the pinnacle of craftsmanship, quality, and sound excellence. Each instrument celebrates Gibson's legacy through accuracy, authenticity, and attention to detail",
    detail: {
      bodyStyle: "ES",
      bodyShape: "ES-355",
      bodyMaterial: "3-ply Maple/Poplar/Maple",
      bodyFinish: "Murphy Lab Aged Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "ES-345-Ebony",
    slug: "es-335-ebony",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/6DV5w7r5SAKlrkaIn1yI6w/1b219868fcee3a38a0ed08f78c4eeace/ES4500EBGH1_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/2RBwiVCRirMXjmzWBG1lJE/ca19a96144f3faf27af7bcfeb1c2bc5a/ES4500EBGH1_side.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/6M0Heafh1xUsEQAxN2C2T8/5a1f8a732746885d1141c3215abec1e4/ES4500EBGH1_beauty.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/7rRZGuzql7F7DNgxr2uCEh/555fdd3ac1759ac35a4f75c9cd026a56/ES4500EBGH1_hs.png?h=1080",
    ],
    highlight: false,
    price: 3899,
    stock: 10,
    category: "Electric",
    subtitle: "The Cornerstone Just Got Smoother",
    description:
      "The Gibson ES-345 boasts a number of aesthetic enhancements over the flagship ES- 335. Crafted with a maple center block and quarter-sawn Adirondack spruce bracing, players will be impressed by the lightweight feel and expanded range of tonal capabilities. The body is wrapped in multi-ply binding and the bound fingerboard has Split Parallelogram inlays exclusive to this model in the ES™ series. The ES-345 is equipped with a variety of high-end appointments like our hand-wired control assembly with Orange Drop® capacitors, Gibson's new Calibrated T-Type humbucking pickups, Vintage Deluxe style tuners, and lightweight aluminum ABR-1 Tune-O-Matic™ bridge and Stop Bar tailpiece anchored with steel thumb-wheels and studs.",
    detail: {
      bodyStyle: "ES",
      bodyShape: "ES-345",
      bodyMaterial: "3-ply Maple/Poplar/Maple",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "Les Paul Classic",
    slug: "les-paul-classic",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/mdpJaYz2cem9MPG7sxa1p/077d1072fbab1fa9de23f78137cda3f5/LPCS00NYNH1_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/7Ciduu4ZCPWRzHQJmF8ATO/396ca7b0bc7286b4ce7a08df49d67661/LPCS00NYNH1_side.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/P3KBX8SGIaNekbJfRuXKo/87f15901a4b6e39c4f4c3e27ed37624c/LPCS00NYNH1_beauty.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/1KSMQlxwvFRFZf8A55OaBn/82d565b06f9e55bf0f3388de4cef5de4/LPCS00NYNH1_hs.png?h=1080",
    ],
    highlight: false,
    price: 2499,
    stock: 15,
    category: "Electric",
    subtitle: "Classic Vibes and Contemporary Performance, Now in Deep Purple",
    description:
      "The Gibson Les Paul™ Classic combines the early 60s style Les Paul model with some functional and time-tested modifications. As expected, the Les Paul Classic is crafted with a mahogany back and maple top coupled with a SlimTaper mahogany neck and a bound rosewood fingerboard. Burstbucker™ 61R & 61T zebra, open-coil pickups provide classic Gibson tones from the era with a bit of extra punch thanks to the open coils. The control assembly features 4 push-pull pots, which provide choices of coil tapping, phase switching, and Pure Bypassing for functional and versatile sonic variety.",
    detail: {
      bodyStyle: "Les Paul",
      bodyShape: "Les Paul",
      bodyMaterial: "Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "Dave Mustaine Flying V EXP Limited Edition ",
    slug: "dave-mustaine-flying-v-exp-limited-edition",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/9fEIkEAYWrzXifYy5BRXh/22586dd2e0ad72b1a6f6ab17ebcb7e6b/CSDMFVEBVONH1_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/3dLBcM8bKM0lLa0C4gNefI/9f7d4e4f9abac007e246cca939c851aa/CSDMFVEBVONH1_side.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/4sk5tsSzaI9M2uXas6e93K/1e4f9ff3465a08ef8d2480e882d59698/CSDMFVEBVONH1_beauty.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/fjCogunoUCXqT4h0Memwr/177bc25a2b746484395859e68abc3688/CSDMFVEBVONH1_hs.png?h=1080",
    ],
    highlight: false,
    price: 6999,
    stock: 3,
    category: "Electric",
    subtitle: "Limited Availability, Unlimited Performance",
    description:
      "Dave Mustaine is the legendary guitarist, vocalist, songwriter, and founder of the multi-platinum selling and Grammy® Award-winning band, MEGADETH. His new Gibson Dave Mustaine Flying V™ EXP Limited Edition delivers the powerful, heavy sound and exceptional playing performance that he demands. The 25.5” scale mahogany neck has a bound ebony fretboard with 24 frets, Mother of Pearl inlays, an Explorer™-style headstock with Grover® Mini Rotomatic® tuners, and a Graph Tech® TUSQ® nut. Dave Mustaine's signature is reproduced on the truss rod cover, and Dave's silhouette is featured on the back of the headstock. The mahogany Flying V-style body has a maple cap (figured maple on the Red Amber Burst version) and is equipped with a Tune-O-Matic™ bridge, a string",
    detail: {
      bodyStyle: "Flying V",
      bodyShape: "Flying V",
      bodyMaterial: "Mahogany",
      bodyFinish:
        "Gloss Nitro. Lacquer (Red Amber Burst), VOS Nitrocellulose Lacquer (Ebony VOS)",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "CS-356 Figured Top",
    slug: "cs-356-figured-top",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/60wiN2TaL5gWygkb2qEccL/1cbcba74aa91505002940d8b2a2cb6c1/CS356FCGH1E_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/26rgRaVXfqpvnQMtH5KxBy/33d42bcbb599dbc18f2a8f24fba77ffe/CS356FCGH1E_side.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/2XP16knQTd0mNbb7AyUW1B/54e6fc7112c74a99d41ca669a65746f7/CS356FCGH1E_beauty.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/6MUiLts8btJANQgsW4cyA3/74dc00452c7499db2490ac17715d30eb/CS356FCGH1E_hs.png?h=1080",
    ],
    highlight: true,
    price: 5499,
    stock: 3,
    category: "Electric",
    subtitle: "Figured Beauty, Solid Tones",
    description:
      "Classic Gibson Custom appointments adorn the Gibson Custom Shop’s CS-356 Figured Top model. While visually similar to Gibson Custom’s ES™ models, the CS-356 is constructed with carved and chambered solid woods, including a stunning figured maple top, for a unique sound all its own that combines elements of archtop, Les Paul™, and semi-hollowbody tones in a deceptive ES-style package. The compact body shape is well balanced and resists feedback while remaining extremely resonant. The sound is captured by a pair of ’57 Classic™ humbucking pickups. The Gibson Custom CS-356 Figured Top",
    detail: {
      bodyStyle: "ES",
      bodyShape: "cs-356",
      bodyMaterial: "Chambered Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "CS-336 Figured Top",
    slug: "cs-336-figured-top",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/1Ew092A24bYJf4QVDeMLoN/0ae929f6bd887c6b866c3932dcad6ae4/CS336FVSNH1_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/6h4us7KJNIRmIwsOa5XG7O/cf6fa9371c3304850dbb2dcb22374495/CS336FVSNH1_side.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/6BlKM8JzV8prrJIMMQmSK0/cd4ec17cea66999e3cef7a8b9aae2963/CS336FVSNH1_beauty.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/323VgAVSYV4Xg1dzGuOkIB/4beb83a5b1581c256166670bd7ebbfa4/CS336FVSNH1_hs.png?h=1080",
    ],
    highlight: true,
    price: 4999,
    stock: 5,
    category: "Electric",
    subtitle: "Semi-Hollow Tones, Solid Performance",
    description:
      "Gibson Custom Shop is the pinnacle of craftsmanship, quality, and sound excellence. Each instrument celebrates Gibson's legacy through accuracy, authenticity, and attention to detail. While visually similar to Gibson Custom’s ES™ models, the CS-336 Figured Top is constructed with carved and chambered solid woods for a sound all its own that combines elements of archtop, Les Paul™, and semi-hollowbody tones. The compact body shape is well balanced and resists feedback while remaining extremely resonant. The sound is captured by a pair of ’57 Classic™ humbucking pickups. Whether you use it on stage or in the studio, the CS-336 Figured Top is a beautiful - and solid - choice!",
    detail: {
      bodyStyle: "ES",
      bodyShape: "CS-336",
      bodyMaterial: "Chambered Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "Les Paul Standard 60s Faded",
    slug: "les-paul-standar-60s-faded",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/1bGDpe1xTLFTkMnvKr94Lg/c7d8fb811cf744bac700d26c99620ef4/LPS6F002HNH1_front__1_.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/yMTShNIBJOFlP51GtvjDw/a466281ae5c38c7e3246acace45264d3/LPS6F002HNH1_side.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/4CpkQxe3f7dN662tBgLP58/003eb16bef736c45c97992e749b0e1a3/LPS6F002HNH1_pups.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/4VY5lkDcjxDq0S29Bv9a9U/675d33831adf8c142fb8b7a3e8d58318/LPS6F002HNH1_hs_front.png?h=1080",
    ],
    highlight: false,
    price: 2499,
    stock: 10,
    category: "Electric",
    subtitle: "A Whole Lotta Les - Now in Faded Dress",
    description:
      "The new Les Paul™ Standard returns to the classic design that made it relevant, played, and loved -- shaping sound across generations and genres of music. It pays tribute to Gibson's Golden Era of innovation and brings authenticity back to life. The Les Paul Standard 60s features a satin nitrocellulose lacquer finish that gives it the look and feel of a long-treasured musical companion. It has a solid mahogany body with an AA figured maple top and a SlimTaper™ 60s-style mahogany neck with a rosewood fingerboard and trapezoid inlays. It's equipped with an ABR-1 Tune-O-Matic™ bridge, aluminum Stop Bar tailpiece, Grover® Rotomatic Kidney tuners, and gold Top Hat knobs with Silver Reflectors and Dial Pointers. The open-coil 60s Burstbucker™ pickups are loaded with A . . .",
    detail: {
      bodyStyle: "Les Paul",
      bodyShape: "Les Paul",
      bodyMaterial: "Mahogany",
      bodyFinish: "Satin Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "SG Standard '61 Faded Maestro Vibrola",
    slug: "sg-standar-61-faded-maestro-vibrol",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/ItfBKLkgZTLCKxKyTKImM/5c77ef946c0f54f6871ccda804422e8b/SG61VF00AYNH1_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/5rrbekLEhGZDZvAEKJZUER/5441b9ae9d71c38664d453376340b341/SG61VF00AYNH1_side.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/3u9IvCSdbCjuVP8UnsR5YX/cc2b70eb1b0c889ed1a78b91dd403693/SG61VF00AYNH1_bridge.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/5wplhsjwgSFiTs7LkcXr8T/5c7d9e5567ad4f1a8c9004ea0f2b86bb/SG61VF00AYNH1_hs.png?h=1080",
    ],
    highlight: true,
    price: 2199,
    stock: 15,
    category: "Electric",
    subtitle: "The Choice of Legends - Now in a Beautiful Faded Finish",
    description:
      "The SG™ Standard ‘61 Faded Maestro™ Vibrola™ returns to the classic design that made it relevant, played, and loved -- shaping sound across generations and genres of music. It features a satin nitrocellulose lacquer finish that gives it the look and feel of a long-treasured musical companion. As the name implies, the Gibson SG Standard '61 Faded Maestro Vibrola also adds vibrato capability. The Maestro Vibrola offers smooth vibrato effects and the classic styling of the Lyre engraving on the tailpiece cover. Standard features include a SlimTaper™ mahogany neck and a bound rosewood fingerboard. The mahogany body features deeply sculpted body scarfing, a 5-ply teardrop pickguard, and a 22nd-fret neck joint. The nickel-plated hardware includes an ABR-1 Tune-O-Matic™ bridge and Keysto ",
    detail: {
      bodyStyle: "SG",
      bodyShape: "SG",
      bodyMaterial: "Mahogany",
      bodyFinish: "Satin Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "Noel Gallagher 1960 ES-355",
    slug: "noel-gallagher-1960-es-355",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/lOtZMlyKWEQTboRk9IVMY/c082e1b6cebda05f8587eebb3f0fa682/60ES355NGASSCBG1_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/03Bk4yZuTPmISZnISxXXp/d3e187c3a63aa2ad397c1a3113937142/60ES355NGASSCBG1_side.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/kw1yz8oZmPqsmbcJ1C8hG/daddd6d8b2d9bd2635f7d22a2131196a/60ES355NGASSCBG1_body.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/196iTav2bjAKbHhDnj0nmW/4cf7c1c8fb2d78f1f3237f83b1b0c333/60ES355NGASSCBG1_headstock.png?h=1080",
    ],
    highlight: false,
    price: 9999,
    stock: 2,
    category: "Electric",
    subtitle: "Someday You Might Find Your Hero",
    description:
      "Noel Gallagher's affiliation with ES™-style guitars stretches back to the beginning of Oasis, the peak of which was in 1997 when he purchased a 1960 Gibson ES-355. Deemed at the time too nice to play, this was initially intended to remain a collector's piece until finally making it to the stage in the early 00s, where it has remained a constant ever since. Now, 20 years later, Gibson Custom is proud to announce the Noel Gallagher 1960 ES-355. Aged by the Murphy Lab and limited to just 200 units globally, this replication will include all the appointments which make the Gibson ES-355 the pinnacle of guitar craftsmanship, including a multi-ply bound maple body, a mahogany neck and ebony fretboard, a Varitone switch, and a Bigsby® B7 vibrato tailpiece. A reproduced",
    detail: {
      bodyStyle: "ES",
      bodyShape: "ES-355",
      bodyMaterial: "Plain Maple Laminate",
      bodyFinish: "Murphy Lab Aged Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "Dave Mustaine Flying V EXP Rust In Peace",
    slug: "dave-mustaine-flying-v-exp-rust-in-peace",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/7EGVlZZhe1yUEQLBQd85hU/786693756ed1660bac3d74eba2b5ff1d/__static.gibson.com_product-images_USA_USA8Y7408_Alien_Tech_Green_front-500_500.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/0V52531MOAE6oFClxzg6o9/a81c8d9183d3aedb2d29733b7279d075/__static.gibson.com_product-images_USA_USA8Y7408_Alien_Tech_Green_DSVX21G1BC1_side.jpg?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/5Rk73a87fYuzjy1NMfKujO/cd3aba4982783e04d8b643f426e53536/__static.gibson.com_product-images_USA_USA8Y7408_Alien_Tech_Green_hardware-500_500.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/6QcDMrBZzHtvKOREkiWsD7/9bed6e42386b1b5fd28598602d0af89d/__static.gibson.com_product-images_USA_USA8Y7408_Alien_Tech_Green_neck-side-500_500.png?h=1080",
    ],
    highlight: false,
    price: 2999,
    stock: 7,
    category: "Electric",
    subtitle: "Designed by Metal Icon Dave Mustaine",
    description:
      "Dave Mustaine is the legendary guitarist, vocalist, songwriter, and founder of the multi-platinum selling and Grammy® Award-winning band, MEGADETH. His new Gibson Dave Mustaine Flying V™ EXP Rust In Peace Artist model delivers the powerful, heavy sound and exceptional playing performance that he demands. The 25.5” scale mahogany neck has an ebony fretboard with a compound fretboard radius, 24 medium jumbo frets, two-tone green/pearloid Rust In Peace diamond inlays, an Explorer™-style headstock with Grover® Mini Rotomatic® tuners with Kidney buttons, a Graph Tech® nut, and Dave Mustaine's signature on the truss rod cover. The mahogany Flying V-style body is equipped with a Tune-O-Matic™ bridge, a Stop Bar tailpiece, and a Dave Mustaine signature Seymour Ducan",
    detail: {
      bodyStyle: "Flying V",
      bodyShape: "Flying V",
      bodyMaterial: "Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },

  {
    brand: "Gibson",
    model: "Keb’ Mo’ “3.0” 12-Fret J-45",
    slug: "keb-mo-3.0-12-fret-j-45",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/24QpbXy6tQaOg1Jm0EMYPI/fe55b0e59925f2bd5e77eed834520185/AMRSKMVS_front_500x500.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/3s9his02lmIo4GZMP2e6dh/1e270adc083fec085a0abbed0564a90f/AMRSKMVS_back.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/4af2JJunjfRBpWLiRG2Smv/736a91348a410e9c628119a0ec51031f/AMRSKMVS_beauty.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/7rJu81iWveAgY1dCgDuEQD/9ef209d1cdf390af997474ddbfea8413/AMRSKMVS_hs.png?h=1080",
    ],
    highlight: false,
    price: 4299,
    stock: 30,
    category: "Acoustic",
    subtitle: "Artist Model 3.0 for Keb’ Mo’",
    description:
      "Gibson is proud to announce the third artist model made in collaboration with multi-talented guitarist, singer, songwriter, and five-time Grammy® award winner Keb’ Mo’ – the Keb’ Mo’ “3.0” 12-Fret J-45™. This new core model is ideal for a wide variety of musical compositions and playing styles and features a thermally aged Sitka spruce top, mahogany back and sides, and a 25” scale mahogany neck with a rosewood fretboard, custom Keb’ Mo’ profile, and open-back Grover® tuners. The neck joins the body at the 12th fret, giving this guitar the rounder, more full-bodied tone and exceptional playing comfort that only a 12-fret neck can provide. Equipped with L.R. Baggs electronics, it's studio and stage-ready, the moment you take it out of the included hardshell case.",
    detail: {
      bodyStyle: "Round Shoulder",
      bodyShape: "J-45",
      bodyMaterial: "Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "The Everly Brothers SJ-200",
    slug: "the-everly-brothers-sj-200",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/1mSDrJcp2mWEYd1tcQnGMF/d8c917258418751961e458d59ec3f342/DTCJBE2EB_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/3uRWp1oklgyhjFPSyUB0sz/213b91f390cf8cf4dee22eef65b3e994/DTCJBE2EB_back.png?h=1080",
      "https://downloads.ctfassets.net/m8onsx4mm13s/5pqvSJM8ZWYSSbdxZeLUAk/5f013639ac33693fb12f6abbe8c76033/DTCJBE2EB_soundhole.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/4TPlbIKPkxQ9yaP4Y5W81e/b9e37d677cc34527b2ed09b2b084573c/DTCJBE2EB_headstock.png?h=1080",
    ],
    highlight: false,
    price: 7999,
    stock: 10,
    category: "Acoustic",
    subtitle: "A Tribute To One of Rock's Greatest Duos",
    description:
      "Phil and Don Everly were music royalty. Members of the Rock and Roll Hall of Fame, the Everly Brothers enjoyed a long string of highly influential hit records driven by their soaring harmonies and propelled by their matching Gibson acoustic guitars. The Gibson Acoustic Custom Shop is proud to celebrate their musical legacy with the release of The Everly Brothers SJ-200. Featuring AA flame maple back and sides paired with a thermally aged Sitka spruce top, which is capped with the dual pickguards that the Everly Brothers made famous. The Everly Brothers SJ-200 also has essential SJ-200 cosmetic features, such as the classic mother of pearl graduated crown inlays on the rosewood fretboard, as well as a Moustache™ bridge with four bar mother of pearl inlays. The bridge saddle, nut, and bri . . .",
    detail: {
      bodyStyle: "Super Jumbo",
      bodyShape: "SJ-200",
      bodyMaterial: "AA Flame Maple",
      bodyFinish: "Thin Finish Nitrocellulose",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "Hummingbird Faded",
    slug: "hummingbird-faded",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/16RB13z7ZmTWndHpncfy2N/eca3cfc0546b5831bc018a6f24454f9b/OCSSHFAN_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/29JX6TD4Pfw4yyAkzzDRpW/b457777f285658a6e547e46d4eb1945c/OCSSHFAN_back.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/4FVLyfWHSaFx4985lxCi08/e86d0927365c0f86b3610ead5bb2cb69/OCSSHFAN_beauty.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/2Qt3ef5qz74lJSxYn50Tny/3530966d12a6241d4237ee11f39790f8/OCSSHFAN_hs.png?h=1080",
    ],
    highlight: false,
    price: 3499,
    stock: 20,
    category: "Acoustic",
    subtitle:
      "One of Gibson's Most Distinguished Acoustics, With a Beautiful Faded Finish",
    description:
      "The unmistakable Gibson Hummingbird™ is followed by the masses as one of the most remarkable acoustic guitars ever built. The new Hummingbird Faded blends vintage appointments and today's modern, high-quality build construction. The Hummingbird Faded is outfitted with gold Gotoh® Keystone tuners, a traditional Hummingbird truss rod cover, and a bone nut and saddle. The built-in LR Baggs VTC electronics make this guitar stage and studio-ready, right out of the included hardshell case.",
    detail: {
      bodyStyle: "Square Shoulder",
      bodyShape: "Hummingbird",
      bodyMaterial: "Mahogany",
      bodyFinish: "Satin Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "J-45 50s Faded",
    slug: "j-45-50s-faded",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/2oxQhASiSAdW2Hbo8fSojz/747da0393b444b1e6de0c275e16f135b/OCRS4FVS_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/1Gd8S4mJi5HrYhzS9kxJOb/e46857bdd6215b2b303816a3ab0f96bd/OCRS4FVS_back.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/23VuyXFVg4JJ0xIguol1Lp/2dc066c8412466e76d869572e443fbce/OCRS4FVS_beauty.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/2Qb06ErwU4KzxzPop8cOBq/6a9c6a8b6f51911bf30560492dbe94fe/OCRS4FVS_hs.png?h=1080",
    ],
    highlight: false,
    price: 2499,
    stock: 40,
    category: "Acoustic",
    subtitle: "The World-Famous Workhorse With a Beautiful Faded Finish",
    description: `The J-45 is Gibson's best-selling acoustic of all time. Nicknamed "The Workhorse" and first introduced in 1942, this iconic acoustic has become the cornerstone of its round-shoulder, dreadnought line. World-renowned for its full, balanced expression, warm bass, and excellent projection, the J-45 has been refined to carry this legacy to new heights. The Gibson J-45 50s Faded delivers full-spectrum sound with incredible dynamic range, warm mids, and tight, punchy bass. Now available with a faded satin nitrocellulose lacquer finish that accentuates the guitar's vintage vibe and equipped with a modern LR Baggs pickup and electronics package for studio and stage use. A hardshell case is also included.`,
    detail: {
      bodyStyle: "Round Shoulder",
      bodyShape: "J-45",
      bodyMaterial: "Mahogany",
      bodyFinish: "Satin Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "Jerry Cantrell Atone Songwriter",
    slug: "jerry-cantrell-atone-songwriter",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/7pT5rswupHe0LpsO0eUJXL/3244cb6aca227791d66c6c290674c5ff/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_AMSSJCEB_front.jpg?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/7lUB0njMDSrf4j1959lLbS/b434ce9fc77c292e97a04ed49ecefdee/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_AMSSJCEB_back.jpg?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/6Ilms9pSy3EPqGhNWHRdNo/c673733d3df30825f9f38ec45e78727b/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_hardware-500_500.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/4x6JQAl8kjXBrJ3fGQvngS/29126b76d33bc2aca1f9c50c977b1786/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_head-640_480.png?h=1080",
    ],
    highlight: false,
    price: 3749,
    stock: 8,
    category: "Acoustic",
    subtitle:
      "An Ideal Blend of Modern and Traditional Features in an Artist Model Acoustic",
    description:
      "Whether you’re writing a song at home, laying it down in the studio, or bringing it to thousands on stage, the Jerry Cantrell “Atone” Songwriter delivers. Made to the Alice in Chains guitarist's specifications and prominently featured in his “Atone” video, the Jerry Cantrell “Atone” Songwriter builds upon the traditional Gibson Songwriter platform. It adds several unique, personalized features, including a thinner body depth for playing comfort, his signature “Circle in Square” pickguard, Jerry Cantrell signature on the truss rod cover, Double J waterslide decal on the back of the headstock, “12” inlay at the 12th fret, gold hardware with gold Grover® Mini Rotomatic® tuners, and an L.R. Baggs™ VTC pickup and preamp so it’s ready to plug in whenever you are.",
    detail: {
      bodyStyle: "Songwriter",
      bodyShape: "Songwriter",
      bodyMaterial: "Rosewood",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "Orianthi SJ-200",
    slug: "orianthi-sj-200",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/0uJafa7UEpR9MEbLNLWc68/5595fa595a853d5147c6c9c0372d1d6f/__static.gibson.com_product-images_Acoustic_ACCXCJ237_Cherry_AMJBOR20CH_front.jpg?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/5uGFmb6MdnKvhb6XWIEGeB/54fb75c12744219e1a2fa2fac827d205/__static.gibson.com_product-images_Acoustic_ACCXCJ237_Cherry_AMJBOR20CH_side.jpg?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/7uTZnt8qT1gpHdv44rlrjn/934f9141db3f3c7ea697b8efcd422d70/__static.gibson.com_product-images_Acoustic_ACCXCJ237_Cherry_hardware-500_500.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/2nKZEaLXnprqRLkFT7BnNh/2cf8dd63e624c821df48f8171d9f2245/__static.gibson.com_product-images_Acoustic_ACCXCJ237_Cherry_neck-side-500_500.png?h=1080",
    ],
    highlight: false,
    price: 5999,
    stock: 3,
    category: "Acoustic",
    subtitle: "A Fiery Guitar for a Fiery Guitarist",
    description:
      "Fiery Australian-born guitarist Orianthi Panagaris has been knocking people out with her playing for over a decade and has played and collaborated with Michael Jackson, Alice Cooper, Carrie Underwood, and Richie Sambora, among others. Now she has a new Gibson signature model, and it's a knockout, too. Featuring an SJ-200 body with a AAA Sitka spruce top and flamed maple back paired with an ES-345 neck, it's definitely a bit different than a standard SJ-200. Other personal touches include an ebony fingerboard with new lotus neck inlays and a mother of pearl Orianthi O symbol on the headstock, gold Grover® Keystone tuners, a distinctive Cherry nitrocellulose lacquer finish, and an LR Baggs™ Orianthi Pickup System that was custom-voiced for Orianthi and features adjustable sat...",
    detail: {
      bodyStyle: "Super Jumbo",
      bodyShape: "SJ-200",
      bodyMaterial: "Maple",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "Cat Stevens J-180 Collector's Edition",
    slug: "cat-stevens-j-180-collector's-edition",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/3yBpd2acGXt7jrNXysDXvI/08b5e56d0293c0d6bf93a803c99f9431/AMJBCSEB_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/7poUR3NjMAaG6T4ws9RfaF/558423d073774c58fa240ddd632338d2/AMJBCSEB_side.png?h=1080",
      "https://downloads.ctfassets.net/m8onsx4mm13s/6ifPM7IVADt5Fw4jaJxl4t/30825ac773af1f5bbabd63da74cdf429/AMJBCSEB_pup.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/39jNCBvAfiUxhajXedPUse/799cefb8372ff9dcf04c110404036100/AMJBCSEB_headstock.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/3E9w3SzXtTBh2l6nQcmUfF/9d5b47d30e1871ef895a6631c7f6e5dd/AMJBCSEB_case_front.png?h=1080",
    ],
    highlight: false,
    price: 7999,
    stock: 2,
    category: "Acoustic",
    subtitle: "A Tribute to One of the World's Greatest Singer-Songwriters.",
    description:
      "With his long dark hair and beard, slender frame, and black Gibson J-180 Cat Stevens stood as the embodiment of the 1970s singer-songwriter, a modern troubadour on a quest for spiritual enlightenment through music. And it was on his J-180 that he wrote and recorded many of his most beloved hits including Wild World, Peace Train, Father and Son, and many more, bought in London’s famous Selmer's Music Shop in 1969, Cat was initially drawn to the J-180’s elegant style, however, its percussive quality soon became an essential component of the intimate sound of his seminal albums ‘Tea For The Tillerman’ and ‘Teaser And The Firecat.’ At the end of the 1970s, Cat sold all of his musical equipment, including his J-180, with the proceeds going to cha . . .",
    detail: {
      bodyStyle: "Jumbo",
      bodyShape: "J-180",
      bodyMaterial: "Maple",
      bodyFinish: "Nitrocellulose VOS",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "Rex Brown Signature Thunderbird",
    slug: "rex-brown-signature-thunderbird",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/48BpKBdOg4LIPSXEPmuaLC/2071fbcb924e3a98c0180a8cced47291/BAT4RB00EBGH1_front.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/7FUfAAvv9LV4UcNsNKylk1/36384193e86d71fd9fc2cc8845afcf14/BAT4RB00EBGH1_side.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/5etNVgkdL6g8LuEyLyZkK/12feddbab6b3bc01b913f7532134d640/BAT4RB00EBGH1_beauty.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/322qeh88CfYM89ziXpd18b/0856d8c5c4334281d785bd67c500118b/BAT4RB00EBGH1_hs_front.png?h=1080",
    ],
    highlight: true,
    price: 2799,
    stock: 12,
    category: "Bass",
    subtitle:
      "An Ideal Blend of Modern and Traditional Features in an Artist Model Acoustic",
    description:
      "Whether you’re writing a song at home, laying it down in the studio, or bringing it to thousands on stage, the Jerry Cantrell “Atone” Songwriter delivers. Made to the Alice in Chains guitarist's specifications and prominently featured in his “Atone” video, the Jerry Cantrell “Atone” Songwriter builds upon the traditional Gibson Songwriter platform. It adds several unique, personalized features, including a thinner body depth for playing comfort, his signature “Circle in Square” pickguard, Jerry Cantrell signature on the truss rod cover, Double J waterslide decal on the back of the headstock, “12” inlay at the 12th fret, gold hardware with gold Grover® Mini Rotomatic® tuners, and an L.R. Baggs™ VTC pickup and preamp so it’s ready to plug in whenever you are.",
    detail: {
      bodyStyle: "Thunderbird",
      bodyShape: "Thunderbird",
      bodyMaterial: "Mahogany ",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Gibson",
    model: "Non-Reverse Thunderbird",
    slug: "non-reverse-thunderbird",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/5AuHYXrV3q4rlUiNhiORbL/a684670e1ae6f3a6192391fd73788c69/__static.gibson.com_product-images_USA_USA7EU389_Inverness_Green_BANT00IGCH1_front.jpg?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/0L6ViMFnrTIC3dvqpe8uRG/4f74ebfeef620cd018d9f88259e1327f/__static.gibson.com_product-images_USA_USA7EU389_Inverness_Green_BANT00IGCH1_side.jpg?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/0RDvEauqdKJ1C07zG1yU7R/d06f5f47cf03c976be375fe1d0a34246/__static.gibson.com_product-images_USA_USA7EU389_Inverness_Green_hardware-500_500.png?h=1080",
      "https://images.ctfassets.net/m8onsx4mm13s/2I1h5dTlqaVaY0HJrMpvKR/bd753d0ebdde791179dc83013581a38c/__static.gibson.com_product-images_USA_USA7EU389_Inverness_Green_neck-side-500_500.png?h=1080",
    ],
    highlight: false,
    price: 2199,
    stock: 15,
    category: "Bass",
    subtitle: "Always Moving Forward",
    description:
      "Ever since it was first released back in 1965, the Non-Reverse Thunderbird has been THE choice for forward-looking bassists who want to make their own path and steadfastly refuse to follow the crowd. The Non-Reverse Thunderbird's distinctive styling and huge, thunderous tone make it a standout on stage and in the studio. Now you have the opportunity to make one of these relatively rare 'birds your own with the release of the new Gibson USA Non-Reverse Thunderbird. Equipped with a Non-Reverse mahogany body and mahogany neck with a rosewood fretboard and 20 medium jumbo frets, each of the two Thunderbird pickups has a volume control, allowing you to use them separately, or to blend them in any amount you prefer. A master tone control rounds out the simple yet highly effective cont . . .",
    detail: {
      bodyStyle: "Thunderbird",
      bodyShape: "Non Reverse Thunderbird",
      bodyMaterial: "Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Fender",
    model: "GOLD FOIL JAZZ BASS",
    slug: "gold-foil-jazz-bass",
    image: [
      "FENDER-PRODUCTS-BASS-1-IMG-1.png",
      "FENDER-PRODUCTS-BASS-1-IMG-2.png",
      "FENDER-PRODUCTS-BASS-1-IMG-3.png",
      "FENDER-PRODUCTS-BASS-1-IMG-4.png",
    ],
    highlight: true,
    price: 1299,
    stock: 25,
    category: "Bass",
    subtitle: "Always Moving Forward",
    description:
      "Inspired by the garage rock bands of the sixties and the cult classic guitars they played, the Gold Foil Collection combines timeless Fender® designs with the dazzling style of a bygone era. The Gold Foil Jazz Bass® features an alder body, mid '60s C-shaped maple neck with bound ebony fingerboard and a Gold Foil single-coil for full, punchy tone that complements the exceptional good looks. Other features include a matching painted headstock, lollipop tuning machines and 20 Medium Jumbo frets.",
    detail: {
      bodyStyle: "Jazz Bass",
      bodyShape: "Jazz",
      bodyMaterial: "Alder",
      bodyFinish: "Gloss Polyester",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Fender",
    model: "GOLD FOIL JAZZMASTER",
    slug: "gold-foil-jazzmaster",
    image: [
      "FENDER-PRODUCTS-ELECTRIC-1-IMG-1.png",
      "FENDER-PRODUCTS-ELECTRIC-1-IMG-2.png",
      "FENDER-PRODUCTS-ELECTRIC-1-IMG-3.png",
      "FENDER-PRODUCTS-ELECTRIC-1-IMG-4.png",
    ],
    highlight: true,
    price: 1399,
    stock: 15,
    category: "Electric",
    subtitle:
      "Gold Foil Jazzmaster: A Vintage-Inspired Fender Collection with Timeless Style and Tone",
    description:
      "Inspired by the garage rock bands of the sixties and the cult classic guitars they played, the Gold Foil Collection combines timeless Fender® designs with the dazzling style of a bygone era. The Gold Foil Jazzmaster® comes equipped with a bound ebony fingerboard, pearloid block inlays, mahogany body, Bigsby® B50 vibrato and three Gold Foil mini-humbuckers. Other features include a matching painted headstock, vintage-style tuners with white buttons, 21 Narrow Tall frets and a Fender® Jaguar®-inspired switch plate.Long on looks and aces in the tone department, the Fender Gold Foil Collection combines the enduring charm of midcentury mail-order guitars with the style and playability of an authentic Fender.",
    detail: {
      bodyStyle: "Jazz",
      bodyShape: "Jazzmaster",
      bodyMaterial: "Mahogany Body",
      bodyFinish: "Gloss Polyester",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Fender",
    model: "JV MODIFIED '60S CUSTOM TELECASTER®",
    slug: "jv-modified-60s-custom-telecaster",
    image: [
      "FENDER-PRODUCTS-ELECTRIC-2-IMG-1.png",
      "FENDER-PRODUCTS-ELECTRIC-2-IMG-2.png",
      "FENDER-PRODUCTS-ELECTRIC-2-IMG-3.png",
      "FENDER-PRODUCTS-ELECTRIC-2-IMG-4.png",
    ],
    highlight: true,
    price: 1399,
    stock: 15,
    category: "Electric",
    subtitle:
      "JV Modified: Vintage Style Meets Modern Playability in Classic Guitars.",
    description:
      "The JV Modified Series combines classic aesthetics with modern playability to suit the needs of today’s guitarist. Taking cues from the now highly sought-after “Japanese Vintage” reissues from the early ‘80s, JV Modified guitars are a refined take on a modern classic.The ’60s Custom Telecaster has a resonant basswood body and is double bound for a touch of elegance. Its dual single-coil pickups are voiced to deliver classic Tele tone. A 4-way switch allows players to quickly select each pickup individually or both pickups in either series or parallel wiring. A push-pull pot on the tone control allows players to flip the pickups in and out of phase in switch positions 2 and 4. The Soft V-shaped maple neck has a silky-smooth satin finish and plays effortlessly thanks to the 9.5radius rosewood fingerboard and medium jumbo frets. For the player seeking classic Fender instruments with a twist, the JV Modified Series delivers a unique combination of vintage Fender style and modern playability.",
    detail: {
      bodyStyle: "Telecaster",
      bodyShape: "Telecaster",
      bodyMaterial: "Basswood",
      bodyFinish: "Gloss Urethane",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Fender",
    model: "JV MODIFIED '60S CUSTOM TELECASTER®",
    slug: "jv-modified-60s-custom-telecaster",
    image: [
      "FENDER-PRODUCTS-ELECTRIC-2-IMG-1.png",
      "FENDER-PRODUCTS-ELECTRIC-2-IMG-2.png",
      "FENDER-PRODUCTS-ELECTRIC-2-IMG-3.png",
      "FENDER-PRODUCTS-ELECTRIC-2-IMG-4.png",
    ],
    highlight: true,
    price: 1399,
    stock: 15,
    category: "Electric",
    subtitle:
      "JV Modified: Vintage Style Meets Modern Playability in Classic Guitars.",
    description:
      "The JV Modified Series combines classic aesthetics with modern playability to suit the needs of today’s guitarist. Taking cues from the now highly sought-after “Japanese Vintage” reissues from the early ‘80s, JV Modified guitars are a refined take on a modern classic.The ’60s Custom Telecaster has a resonant basswood body and is double bound for a touch of elegance. Its dual single-coil pickups are voiced to deliver classic Tele tone. A 4-way switch allows players to quickly select each pickup individually or both pickups in either series or parallel wiring. A push-pull pot on the tone control allows players to flip the pickups in and out of phase in switch positions 2 and 4. The Soft V-shaped maple neck has a silky-smooth satin finish and plays effortlessly thanks to the 9.5radius rosewood fingerboard and medium jumbo frets. For the player seeking classic Fender instruments with a twist, the JV Modified Series delivers a unique combination of vintage Fender style and modern playability.",
    detail: {
      bodyStyle: "Telecaster",
      bodyShape: "Telecaster",
      bodyMaterial: "Basswood",
      bodyFinish: "Gloss Urethane",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Neumann",
    model: "KH 310 A L G",
    slug: "kh-310-a-l-g",
    image: [
      "NEUMANN-PRODUCTS-1-IMG-1.png",
      "NEUMANN-PRODUCTS-1-IMG-2.png",
      "NEUMANN-PRODUCTS-1-IMG-3.png",
      "NEUMANN-PRODUCTS-1-IMG-4.png",
    ],
    highlight: false,
    price: 2599,
    stock: 30,
    category: "AudioPro",
    subtitle:
      "High-resolution tri-amplified near-field monitor, optimized for midrange and a dry bass sound.",
    description:
      "The KH 310 has been developed true to the Neumann philosophy for monitor loudspeakers. Every component, every shape, every signal and every wave motion is a consequence of this philosophy. No form or component is there without reason. There are hundreds of tangible reasons built into the KH 310, which all stand for exceptionally pure and neutral sound. These include, for example, curvatures of the housing that reduce edge diffraction. Also included is the pistonic output of the bass driver which does not give rise to harmonic distortions, even with the highest sound peaks. Some of these reasons are obvious in the KH 310. Others Neumann prefers to keep to itself. But together, each can be heard – sound professionals in both large and small studios all around the world can testify to this",
    detail: {
      freeFieldFrequencyResponse6Db: "30 Hz … 22 kHz",
      freeFieldFrequencyResponse3Db: "34 Hz … 21 kHz",
      freeFieldFrequencyLinearityDeviationBetween100HzAnd10Khz: "± 1.1 dB",
      selfGeneratedNoiseAt10CmWithInputGainSetTo100DbSPLFor0Dbu:
        "<20 dB(A) SPL",
      sineWaveOutputWithATHDOf05PercentAt1MInHalfSpace: "95 dB SPL (>85 Hz)",
      maxSPLCalcInHalfSpaceAt3PercentTHDAt1mAveragedBetween100HzAnd6Khz:
        "116.3 dB SPL",
      maxSPLInFullSpaceAt3PercentTHDAt1mAveragedBetween100HzAnd6Khz:
        "110.3 dB SPL",
      bassCapabilityMaxSPLInHalfSpaceAt3PercentTHDAt1mAveragedBetween50HzAnd100Hz:
        "106.8 dB SPL",
      reproductionAccuracyBetween100HzAnd10Khz100808050OfLoudspeakersProduced:
        "±0.87; ±0.39; ±0.23 dB",
      displayBrightness: "White: 100%/60%/30%/off; Red: 100%/60%/30%",
    },
  },
  {
    brand: "Neumann",
    model: "V 402",
    slug: "v-402",
    image: ["NEUMANN-PRODUCTS-2-IMG-1.png", "NEUMANN-PRODUCTS-2-IMG-2.png"],
    highlight: false,
    price: 3599,
    stock: 30,
    category: "AudioPro",
    subtitle: "DISCOVER THE TRUE VOICE OF YOUR MICROPHONES",
    description:
      "The V 402 is a state-of-the art dual channel microphone preamplifier with an integrated studio grade headphone amplifier. Its transformerless circuitry is designed for maximum transparency and sonic purity. The V 402 is thus the perfect complement to all Neumann microphones in order to unveil the true character of voices and instruments.",
    detail: {
      frequencyRange: "<10 Hz to >100 kHz (-3 dB@ 40 dB Gain)",
      mainsPowerSupply: {
        inputVoltage: "100-120 V and 220-240 V",
        frequency: "50 Hz/60 Hz",
      },
      powerConsumption: "max. 25 W",
      microphoneInputs: {
        connector: "2 x XLR 3 F",
        inputImpedance: "approx. 3 kΩ",
        minimumGain: "+20 dB (PAD off)",
        maximumGain: "+60 dB (PAD off)",
        attenuationPADSwitchable: "off/-20 dB",
        maximumInputLevelPADOff: "+8 dBu",
        maximumInputLevelPADOn: "+28 dBu",
        EIN60dBGain50Ohm: "-129,4 dBu(A)",
        EIN40dBGain50Ohm: "-129,2 dBu(A)",
        THDMicIn1kHz40dBGain12dBu: "0,00018%",
      },
      powerSupply: {
        P48: "48 V",
        maxCurrent: "≥ 10 mA",
        switchable: "on/off",
      },
      hiZInputs: {
        active: "switchable on/off",
        connector: "2 x Jack 6.3 mm (1/4”), mono, unbalanced (front)",
        inputImpedance: "3.3 MΩ",
        maximumInputLevel: "+21 dBu",
        minimumGain: "0 dB (PAD off)",
        maximumGain: "+40 dB (PAD off)",
      },
    },
  },
  {
    brand: "Neumann",
    model: "U 67 Set",
    slug: "u-67-set",
    image: [
      "NEUMANN-PRODUCTS-3-IMG-1.png",
      "NEUMANN-PRODUCTS-3-IMG-2.png",
      "NEUMANN-PRODUCTS-3-IMG-3.png",
      "NEUMANN-PRODUCTS-3-IMG-4.png",
      "NEUMANN-PRODUCTS-3-IMG-5.png",
    ],
    highlight: false,
    price: 3599,
    stock: 10,
    category: "AudioPro",
    subtitle: "RETURN OF A LEGEND",
    description:
      "Introduced as the successor to the eminent Neumann U 47, a lesser microphone would have failed. But the U 67 was quickly adopted as the new studio standard, offering many advantages over its predecessor. With three selectable polar patterns and advanced tube circuitry, including low cut and pad switches, the Neumann U 67 was well-equipped for virtually any recording task. It still is: To this day, many top level engineers would choose the U 67 as their “desert island” microphone for its extraordinary versatility and unmatched sound quality.",
    detail: {
      acousticalOperatingPrinciple: "Pressure gradient transducer",
      directionalPattern: "Omnidirectional, cardioid, figure-8",
      frequencyRange: "20 Hz ... 20 kHz",
      sensitivity: "15/24/16 mV/Pa ± 1 dB (Omni/cardioid/8)",
      ratedImpedance: "200 ohms",
      ratedLoadImpedance: "1 kohms",
      equivalentNoiseLevelCCIR: "32/28/31 dB (Omni/cardioid/8)",
      equivalentNoiseLevelAWeighted: "21/17/20 dB-A (Omni/cardioid/8)",
      maximumSPL: "114 dB (cardioid)",
      maximumSPLwithPreattenuation: "124 dB",
      signalToNoiseRatioCCIR: "62/66/63 dB (Omni/cardioid/8)",
      signalToNoiseRatioAWeighted: "73/77/74 dB (Omni/cardioid/8)",
      maximumOutputVoltage: "-9.8 dBu",
      supplyVoltage: "48 V ± 4 V",
      currentConsumption: "3.5 mA",
      matchingConnector: "Microphone: spec. 7pin, Power Supply: XLR 3 F",
      weight: "560 g",
      diameter: "56 mm",
      length: "200 mm",
    },
  },
  {
    brand: "PRS",
    model: "GRAINGER 5 STRING BASS",
    slug: "graninger-5-string-bass",
    image: [
      "PRS-PRODUCTS-BASS-1-IMG-1.png",
      "PRS-PRODUCTS-BASS-1-IMG-2.png",
      "PRS-PRODUCTS-BASS-1-IMG-3.png",
    ],
    highlight: true,
    price: 2599,
    stock: 15,
    category: "Bass",
    subtitle: "Endless Features For Studio And Stage",
    description:
      "The Grainger 5 is the evolution of our Private Stock Gary Grainger Bass line. As the primary designer of our Private Stock basses, Gary (John Scofield, Dennis Chambers, Frank Gambali, etc.) collaborated with many bass artists, including Wyzard (Mother’s Finest) and Kevin Walker (Justin Timberlake), to create a Core PRS bass with all the character and quality of Gary’s Private Stock models but with a more universal appeal.",
    detail: {
      bodyStyle: "Solidbody",
      bodyShape: "PRS original",
      bodyMaterial: "Maple",
      bodyFinish: "Gloss Polyester",
      profile: "Artist Profile",
      fingerboardRadius: "304.8 mm / 12 in",
      nutMaterial: "Graph Tech",
      inlays: "Acrylic Dot",
      scaleLength: "628.65 mm / 24.75 in",
      fretCount: "2",
      nutWidth: "43.053 mm / 1.695 in",
      joint: "Glued In, Set Neck",
      fingerBoardMaterial: "Rosewood",
      frets: "Medium Jumbo",
      endOfBoardWidth: "57.404 mm / 2.26 in",
      finish: "Nickel",
      pickguard:
        "Black Multi-ply (Silver Mist), Acrylic Tortoise Shell (Vintage Ebony Gloss)",
      controlKnobs: "Black Top Hat",
      bridge: "Aluminium Wraparaound",
      trussRod: "Adjustable",
      strapButtons: "2",
      tunningMachines: "Vintage Deluxe with White Buttons",
      trusRodCover: "2-ply Bell; Black and White",
      bridgePickup: "P-90 DC Dogear",
      controls:
        "Master Volume, Master Tone, Hand-Wired with Orange Drop Capacitors",
      outputJack: "1/4",
      stringGauge: ".010 .013 .017 .026 .036 .046",
      case: "Custom Artist Signature Protector Hardshell Case",
      accessories: "Original Accesory Kit",
    },
  },
  {
    brand: "Universal Audio",
    model: "APOLLO TWIN X",
    slug: "apollo-twin-x",
    image: [
      "UA-PRODUCTS-1-IMG-1.png",
      "UA-PRODUCTS-1-IMG-2.png",
      "UA-PRODUCTS-1-IMG-3.png",
      "UA-PRODUCTS-1-IMG-4.png",
    ],
    highlight: false,
    price: 2599,
    stock: 5,
    category: "AudioPro",
    subtitle: "Get hit-making results with the world's best desktop interface.",
    description:
      "Apollo Twin X gives musicians and producers elite-class audio conversion with the tone, feel, and flow of analog recording. Letting you record through preamps from Neve, API, Manley, and more — with near‑zero latency — Apollo Twin X is born to make records.",
    detail: {
      acousticalOperatingPrinciple: "Pressure gradient transducer",
      directionalPattern: "Omnidirectional, cardioid, figure-8",
      frequencyRange: "20 Hz ... 20 kHz",
      sensitivity: "15/24/16 mV/Pa ± 1 dB (Omni/cardioid/8)",
      ratedImpedance: "200 ohms",
      ratedLoadImpedance: "1 kohms",
      equivalentNoiseLevelCCIR: "32/28/31 dB (Omni/cardioid/8)",
      equivalentNoiseLevelAWeighted: "21/17/20 dB-A (Omni/cardioid/8)",
      maximumSPL: "114 dB (cardioid)",
      maximumSPLwithPreattenuation: "124 dB",
      signalToNoiseRatioCCIR: "62/66/63 dB (Omni/cardioid/8)",
      signalToNoiseRatioAWeighted: "73/77/74 dB (Omni/cardioid/8)",
      maximumOutputVoltage: "-9.8 dBu",
      supplyVoltage: "48 V ± 4 V",
      currentConsumption: "3.5 mA",
      matchingConnector: "Microphone: spec. 7pin, Power Supply: XLR 3 F",
      weight: "560 g",
      diameter: "56 mm",
      length: "200 mm",
    },
  },
  {
    brand: "Universal Audio",
    model: "APOLLO TWIN X",
    slug: "apollo-twin-x",
    image: [
      "UA-PRODUCTS-2-IMG-1.png",
      "UA-PRODUCTS-2-IMG-2.png",
      "UA-PRODUCTS-2-IMG-3.png",
      "UA-PRODUCTS-2-IMG-4.png",
    ],
    highlight: true,
    price: 4599,
    stock: 5,
    category: "AudioPro",
    subtitle: "Produce album-ready sounds in realtime.",
    description:
      "Apollo x8 gives creators running bigger project and bedroom studios the same professional analog tones heard on your favorite records. With elite‑class conversion and HEXA Core UAD plug-in processing, Apollo x8 is the only interface that lets you record through preamps from Neve, API, Manley, and more — with near‑zero latency — giving you professional sound in a sleek rackmount Thunderbolt 3 audio interface.",
    detail: {
      acousticalOperatingPrinciple: "Pressure gradient transducer",
      directionalPattern: "Omnidirectional, cardioid, figure-8",
      frequencyRange: "20 Hz ... 20 kHz",
      sensitivity: "15/24/16 mV/Pa ± 1 dB (Omni/cardioid/8)",
      ratedImpedance: "200 ohms",
      ratedLoadImpedance: "1 kohms",
      equivalentNoiseLevelCCIR: "32/28/31 dB (Omni/cardioid/8)",
      equivalentNoiseLevelAWeighted: "21/17/20 dB-A (Omni/cardioid/8)",
      maximumSPL: "114 dB (cardioid)",
      maximumSPLwithPreattenuation: "124 dB",
      signalToNoiseRatioCCIR: "62/66/63 dB (Omni/cardioid/8)",
      signalToNoiseRatioAWeighted: "73/77/74 dB (Omni/cardioid/8)",
      maximumOutputVoltage: "-9.8 dBu",
      supplyVoltage: "48 V ± 4 V",
      currentConsumption: "3.5 mA",
      matchingConnector: "Microphone: spec. 7pin, Power Supply: XLR 3 F",
      weight: "560 g",
      diameter: "56 mm",
      length: "200 mm",
    },
  },
];

module.exports = products;
