const products = [
  {
    brand: "Gibson",
    model: "Billie Joe Armstrong Les Paul Junior",
    slug: "billie-joe-armstrong-les-paul-junior",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/67WERaCwmv87IOWYsXVBLB/70b5d45e9a6512f39f40c432b7e6aff8/LPJRBA22S1NH1_front.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/52LN0tVh4sQivTzzW4aDC0/f2e2d58462b0d6e5122ffb0c35d630c8/LPJRBA22S1NH1_side.png",
      "https://images.ctfassets.net/m8onsx4mm13s/3l4dOSNF6acZotFszSJV2F/ea443c0426e122864c924ac519cd23e2/LPJRBA22S1NH1_beauty.png",
      "https://www.gibson.com/en-US/Electric-Guitar/USA8SV133/Silver-Mist",
    ],
    highlight: false,
    price: 2199,
    stock: 10,
    category: "Electric",
    subtitle: "Designed by the Green Day Punk Rock Legend",
    description:
      "The new Billie Joe Armstrong Les Paul™ Junior is an exceptional guitar to rock out on, whether you play rock or punk. Designed in collaboration with Green Day’s legendary guitarist, it has everything you need for great tone with no frills to get in your way, including a mahogany neck with a Billie Joe Armstrong SlimTaper™ profile, rosewood fretboard, Graph Tech® nut, and Billie Joe’s signature on the truss rod cover. The mahogany body is equipped with a wraparound bridge/tailpiece and a P-90 DC Dogear pickup. The P-90 DC is our latest hum-canceling design. It features a modernized version of the Sidewinder dual-coil technology that was first developed by Seth Lover in 1958, delivering a hum-free P-90 with the most authentic P-90 tonality yet, retaining the classic sound of a single",
    detail: {
      bodyStyle: "Les Paul",
      bodyShape: "Les Paul Junior",
      bodyMaterial: "Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "B.B. King Live at the Regal ES-335",
    slug: "bb-king-live-at-the-regal-es-335",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/3djWs8U7hFdy2TeDVWS4Cu/762d54683ad54e44aae82c988529cfbe/BBES335REAGNB1_front.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/O2zMaCOUsZOkobeTppUqK/81fc86c9d3dc4a70f44381d444a4ea01/BBES335REAGNB1_side.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/wdTGz0uHlzK6uNGcb0Dy9/291c72472f79310d0428cd7f79e94418/BBES335REAGNB1_beauty.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/17rjBaf7yIK9QvPr9pdATJ/74c1d331c951e5bac332bc8bd0661817/BBES335REAGNB1_hs.png?h=900",
    ],
    highlight: false,
    price: 9999,
    stock: 3,
    category: "Electric",
    subtitle:
      "A Faithful Tribute to a Live Music Icon and a Legendary Guitarist",
    description:
      "Gibson Custom Shop is the pinnacle of craftsmanship, quality, and sound excellence. Each instrument celebrates Gibson's legacy through accuracy, authenticity, and attention to detail",
    detail: {
      bodyStyle: "ES",
      bodyShape: "ES-355",
      bodyMaterial: "3-ply Maple/Poplar/Maple",
      bodyFinish: "Murphy Lab Aged Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "ES-345-Ebony",
    slug: "es-335-ebony",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/12TXJZn8a162RJOkPy6Id6/6aeeeacc99df81e32cd8dbfedecb1d40/front-500_500.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/2RBwiVCRirMXjmzWBG1lJE/ca19a96144f3faf27af7bcfeb1c2bc5a/ES4500EBGH1_side.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/6M0Heafh1xUsEQAxN2C2T8/5a1f8a732746885d1141c3215abec1e4/ES4500EBGH1_beauty.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/7rRZGuzql7F7DNgxr2uCEh/555fdd3ac1759ac35a4f75c9cd026a56/ES4500EBGH1_hs.png?h=900",
    ],
    highlight: false,
    price: 3899,
    stock: 10,
    category: "Electric",
    subtitle: "The Cornerstone Just Got Smoother",
    description:
      "The Gibson ES-345 boasts a number of aesthetic enhancements over the flagship ES- 335. Crafted with a maple center block and quarter-sawn Adirondack spruce bracing, players will be impressed by the lightweight feel and expanded range of tonal capabilities. The body is wrapped in multi-ply binding and the bound fingerboard has Split Parallelogram inlays exclusive to this model in the ES™ series. The ES-345 is equipped with a variety of high-end appointments like our hand-wired control assembly with Orange Drop® capacitors, Gibson's new Calibrated T-Type humbucking pickups, Vintage Deluxe style tuners, and lightweight aluminum ABR-1 Tune-O-Matic™ bridge and Stop Bar tailpiece anchored with steel thumb-wheels and studs.",
    detail: {
      bodyStyle: "ES",
      bodyShape: "ES-345",
      bodyMaterial: "3-ply Maple/Poplar/Maple",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "Les Paul Classic",
    slug: "les-paul-classic",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/iMwUxsLEderS7Pfuhw4tj/998c84993a119646749c2e29f3566447/LPCS00NYNH1_front_500x500.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/7Ciduu4ZCPWRzHQJmF8ATO/396ca7b0bc7286b4ce7a08df49d67661/LPCS00NYNH1_side.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/P3KBX8SGIaNekbJfRuXKo/87f15901a4b6e39c4f4c3e27ed37624c/LPCS00NYNH1_beauty.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/1KSMQlxwvFRFZf8A55OaBn/82d565b06f9e55bf0f3388de4cef5de4/LPCS00NYNH1_hs.png?h=900",
    ],
    highlight: false,
    price: 2499,
    stock: 15,
    category: "Electric",
    subtitle: "Classic Vibes and Contemporary Performance, Now in Deep Purple",
    description:
      "The Gibson Les Paul™ Classic combines the early 60s style Les Paul model with some functional and time-tested modifications. As expected, the Les Paul Classic is crafted with a mahogany back and maple top coupled with a SlimTaper mahogany neck and a bound rosewood fingerboard. Burstbucker™ 61R & 61T zebra, open-coil pickups provide classic Gibson tones from the era with a bit of extra punch thanks to the open coils. The control assembly features 4 push-pull pots, which provide choices of coil tapping, phase switching, and Pure Bypassing for functional and versatile sonic variety.",
    detail: {
      bodyStyle: "Les Paul",
      bodyShape: "Les Paul",
      bodyMaterial: "Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "Dave Mustaine Flying V EXP Limited Edition ",
    slug: "dave-mustaine-flying-v-exp-limited-edition",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/9fEIkEAYWrzXifYy5BRXh/22586dd2e0ad72b1a6f6ab17ebcb7e6b/CSDMFVEBVONH1_front.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/3dLBcM8bKM0lLa0C4gNefI/9f7d4e4f9abac007e246cca939c851aa/CSDMFVEBVONH1_side.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4sk5tsSzaI9M2uXas6e93K/1e4f9ff3465a08ef8d2480e882d59698/CSDMFVEBVONH1_beauty.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/fjCogunoUCXqT4h0Memwr/177bc25a2b746484395859e68abc3688/CSDMFVEBVONH1_hs.png?h=900",
    ],
    highlight: false,
    price: 6999,
    stock: 3,
    category: "Electric",
    subtitle: "Limited Availability, Unlimited Performance",
    description:
      "Dave Mustaine is the legendary guitarist, vocalist, songwriter, and founder of the multi-platinum selling and Grammy® Award-winning band, MEGADETH. His new Gibson Dave Mustaine Flying V™ EXP Limited Edition delivers the powerful, heavy sound and exceptional playing performance that he demands. The 25.5” scale mahogany neck has a bound ebony fretboard with 24 frets, Mother of Pearl inlays, an Explorer™-style headstock with Grover® Mini Rotomatic® tuners, and a Graph Tech® TUSQ® nut. Dave Mustaine's signature is reproduced on the truss rod cover, and Dave's silhouette is featured on the back of the headstock. The mahogany Flying V-style body has a maple cap (figured maple on the Red Amber Burst version) and is equipped with a Tune-O-Matic™ bridge, a string",
    detail: {
      bodyStyle: "Flying V",
      bodyShape: "Flying V",
      bodyMaterial: "Mahogany",
      bodyFinish:
        "Gloss Nitro. Lacquer (Red Amber Burst), VOS Nitrocellulose Lacquer (Ebony VOS)",
    },
  },
  {
    brand: "Gibson",
    model: "CS-356 Figured Top",
    slug: "cs-356-figured-top",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/2D998OCqePikgtQVYzAbMA/167345e3f4a7eea0806bc7fc0da1354f/CS356FCGH1E_front_500x500.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/26rgRaVXfqpvnQMtH5KxBy/33d42bcbb599dbc18f2a8f24fba77ffe/CS356FCGH1E_side.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/2XP16knQTd0mNbb7AyUW1B/54e6fc7112c74a99d41ca669a65746f7/CS356FCGH1E_beauty.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/6MUiLts8btJANQgsW4cyA3/74dc00452c7499db2490ac17715d30eb/CS356FCGH1E_hs.png?h=900",
    ],
    highlight: false,
    price: 5499,
    stock: 3,
    category: "Electric",
    subtitle: "Figured Beauty, Solid Tones",
    description:
      "Classic Gibson Custom appointments adorn the Gibson Custom Shop’s CS-356 Figured Top model. While visually similar to Gibson Custom’s ES™ models, the CS-356 is constructed with carved and chambered solid woods, including a stunning figured maple top, for a unique sound all its own that combines elements of archtop, Les Paul™, and semi-hollowbody tones in a deceptive ES-style package. The compact body shape is well balanced and resists feedback while remaining extremely resonant. The sound is captured by a pair of ’57 Classic™ humbucking pickups. The Gibson Custom CS-356 Figured Top",
    detail: {
      bodyStyle: "ES",
      bodyShape: "cs-356",
      bodyMaterial: "Chambered Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "CS-336 Figured Top",
    slug: "cs-336-figured-top",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/7r4dZic5HIJpi8W1gnrNXv/81c53c046bf30d282a78d8defd814909/CS336FVSNH1_front_500x500.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/6h4us7KJNIRmIwsOa5XG7O/cf6fa9371c3304850dbb2dcb22374495/CS336FVSNH1_side.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/6BlKM8JzV8prrJIMMQmSK0/cd4ec17cea66999e3cef7a8b9aae2963/CS336FVSNH1_beauty.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/323VgAVSYV4Xg1dzGuOkIB/4beb83a5b1581c256166670bd7ebbfa4/CS336FVSNH1_hs.png?h=900",
    ],
    highlight: false,
    price: 4999,
    stock: 5,
    category: "Electric",
    subtitle: "Semi-Hollow Tones, Solid Performance",
    description:
      "Gibson Custom Shop is the pinnacle of craftsmanship, quality, and sound excellence. Each instrument celebrates Gibson's legacy through accuracy, authenticity, and attention to detail. While visually similar to Gibson Custom’s ES™ models, the CS-336 Figured Top is constructed with carved and chambered solid woods for a sound all its own that combines elements of archtop, Les Paul™, and semi-hollowbody tones. The compact body shape is well balanced and resists feedback while remaining extremely resonant. The sound is captured by a pair of ’57 Classic™ humbucking pickups. Whether you use it on stage or in the studio, the CS-336 Figured Top is a beautiful - and solid - choice!",
    detail: {
      bodyStyle: "ES",
      bodyShape: "CS-336",
      bodyMaterial: "Chambered Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "Les Paul Standard 60s Faded",
    slug: "les-paul-standar-60s-faded",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/6MxQ8vJFZ5tQmfl7tII1OJ/c2ccc7ac14a18e42d9a4e510c5ebd014/LPS6F002HNH1_front.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/yMTShNIBJOFlP51GtvjDw/a466281ae5c38c7e3246acace45264d3/LPS6F002HNH1_side.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4CpkQxe3f7dN662tBgLP58/003eb16bef736c45c97992e749b0e1a3/LPS6F002HNH1_pups.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4VY5lkDcjxDq0S29Bv9a9U/675d33831adf8c142fb8b7a3e8d58318/LPS6F002HNH1_hs_front.png?h=900",
    ],
    highlight: false,
    price: 2499,
    stock: 10,
    category: "Electric",
    subtitle: "A Whole Lotta Les - Now in Faded Dress",
    description:
      "The new Les Paul™ Standard returns to the classic design that made it relevant, played, and loved -- shaping sound across generations and genres of music. It pays tribute to Gibson's Golden Era of innovation and brings authenticity back to life. The Les Paul Standard 60s features a satin nitrocellulose lacquer finish that gives it the look and feel of a long-treasured musical companion. It has a solid mahogany body with an AA figured maple top and a SlimTaper™ 60s-style mahogany neck with a rosewood fingerboard and trapezoid inlays. It's equipped with an ABR-1 Tune-O-Matic™ bridge, aluminum Stop Bar tailpiece, Grover® Rotomatic Kidney tuners, and gold Top Hat knobs with Silver Reflectors and Dial Pointers. The open-coil 60s Burstbucker™ pickups are loaded with A . . .",
    detail: {
      bodyStyle: "Les Paul",
      bodyShape: "Les Paul",
      bodyMaterial: "Mahogany",
      bodyFinish: "Satin Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "SG Standard '61 Faded Maestro Vibrola",
    slug: "sg-standar-61-faded-maestro-vibrol",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/ItfBKLkgZTLCKxKyTKImM/5c77ef946c0f54f6871ccda804422e8b/SG61VF00AYNH1_front.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/5rrbekLEhGZDZvAEKJZUER/5441b9ae9d71c38664d453376340b341/SG61VF00AYNH1_side.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/3u9IvCSdbCjuVP8UnsR5YX/cc2b70eb1b0c889ed1a78b91dd403693/SG61VF00AYNH1_bridge.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/5wplhsjwgSFiTs7LkcXr8T/5c7d9e5567ad4f1a8c9004ea0f2b86bb/SG61VF00AYNH1_hs.png?h=900",
    ],
    highlight: false,
    price: 2199,
    stock: 15,
    category: "Electric",
    subtitle: "The Choice of Legends - Now in a Beautiful Faded Finish",
    description:
      "The SG™ Standard ‘61 Faded Maestro™ Vibrola™ returns to the classic design that made it relevant, played, and loved -- shaping sound across generations and genres of music. It features a satin nitrocellulose lacquer finish that gives it the look and feel of a long-treasured musical companion. As the name implies, the Gibson SG Standard '61 Faded Maestro Vibrola also adds vibrato capability. The Maestro Vibrola offers smooth vibrato effects and the classic styling of the Lyre engraving on the tailpiece cover. Standard features include a SlimTaper™ mahogany neck and a bound rosewood fingerboard. The mahogany body features deeply sculpted body scarfing, a 5-ply teardrop pickguard, and a 22nd-fret neck joint. The nickel-plated hardware includes an ABR-1 Tune-O-Matic™ bridge and Keysto ",
    detail: {
      bodyStyle: "SG",
      bodyShape: "SG",
      bodyMaterial: "Mahogany",
      bodyFinish: "Satin Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "Noel Gallagher 1960 ES-355",
    slug: "noel-gallagher-1960-es-355",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/lOtZMlyKWEQTboRk9IVMY/c082e1b6cebda05f8587eebb3f0fa682/60ES355NGASSCBG1_front.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/03Bk4yZuTPmISZnISxXXp/d3e187c3a63aa2ad397c1a3113937142/60ES355NGASSCBG1_side.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/kw1yz8oZmPqsmbcJ1C8hG/daddd6d8b2d9bd2635f7d22a2131196a/60ES355NGASSCBG1_body.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/196iTav2bjAKbHhDnj0nmW/4cf7c1c8fb2d78f1f3237f83b1b0c333/60ES355NGASSCBG1_headstock.png?h=900",
    ],
    highlight: false,
    price: 9999,
    stock: 2,
    category: "Electric",
    subtitle: "Someday You Might Find Your Hero",
    description:
      "Noel Gallagher's affiliation with ES™-style guitars stretches back to the beginning of Oasis, the peak of which was in 1997 when he purchased a 1960 Gibson ES-355. Deemed at the time too nice to play, this was initially intended to remain a collector's piece until finally making it to the stage in the early 00s, where it has remained a constant ever since. Now, 20 years later, Gibson Custom is proud to announce the Noel Gallagher 1960 ES-355. Aged by the Murphy Lab and limited to just 200 units globally, this replication will include all the appointments which make the Gibson ES-355 the pinnacle of guitar craftsmanship, including a multi-ply bound maple body, a mahogany neck and ebony fretboard, a Varitone switch, and a Bigsby® B7 vibrato tailpiece. A reproduced",
    detail: {
      bodyStyle: "ES",
      bodyShape: "ES-355",
      bodyMaterial: "Plain Maple Laminate",
      bodyFinish: "Murphy Lab Aged Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "Dave Mustaine Flying V EXP Rust In Peace",
    slug: "dave-mustaine-flying-v-exp-rust-in-peace",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/7EGVlZZhe1yUEQLBQd85hU/786693756ed1660bac3d74eba2b5ff1d/__static.gibson.com_product-images_USA_USA8Y7408_Alien_Tech_Green_front-500_500.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/0V52531MOAE6oFClxzg6o9/a81c8d9183d3aedb2d29733b7279d075/__static.gibson.com_product-images_USA_USA8Y7408_Alien_Tech_Green_DSVX21G1BC1_side.jpg?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/5Rk73a87fYuzjy1NMfKujO/cd3aba4982783e04d8b643f426e53536/__static.gibson.com_product-images_USA_USA8Y7408_Alien_Tech_Green_hardware-500_500.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/6QcDMrBZzHtvKOREkiWsD7/9bed6e42386b1b5fd28598602d0af89d/__static.gibson.com_product-images_USA_USA8Y7408_Alien_Tech_Green_neck-side-500_500.png?h=900",
    ],
    highlight: false,
    price: 2999,
    stock: 7,
    category: "Electric",
    subtitle: "Designed by Metal Icon Dave Mustaine",
    description:
      "Dave Mustaine is the legendary guitarist, vocalist, songwriter, and founder of the multi-platinum selling and Grammy® Award-winning band, MEGADETH. His new Gibson Dave Mustaine Flying V™ EXP Rust In Peace Artist model delivers the powerful, heavy sound and exceptional playing performance that he demands. The 25.5” scale mahogany neck has an ebony fretboard with a compound fretboard radius, 24 medium jumbo frets, two-tone green/pearloid Rust In Peace diamond inlays, an Explorer™-style headstock with Grover® Mini Rotomatic® tuners with Kidney buttons, a Graph Tech® nut, and Dave Mustaine's signature on the truss rod cover. The mahogany Flying V-style body is equipped with a Tune-O-Matic™ bridge, a Stop Bar tailpiece, and a Dave Mustaine signature Seymour Ducan",
    detail: {
      bodyStyle: "Flying V",
      bodyShape: "Flying V",
      bodyMaterial: "Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "Sergio Vallin 1955 Les Paul Goldtop",
    slug: "sergio-vallin-1955-les-paul-goldtop",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/5nH8rnG69e9iBt9o9OGJaI/73ce591572d9f2e392e72a365c7950a6/front-500_500.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/2UqEcjgjhEVnkDEgmiJ2sA/7cd86459882c45f293b590daf1ae6d33/back-neck-500_500.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/6ioH5jdMPCoONKeoxgEEkQ/21e98b6cb9d7562faa706b5f07e543a5/hardware-500_500.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4oCytjawoKvTRH4pejgozo/ad86743cd6480b69f9aa2c56c0fc63ec/head-500_500.png?h=900",
    ],
    highlight: false,
    price: 7999,
    stock: 5,
    category: "Electric",
    subtitle: "A Goldtop With Lots of Positive Energy",
    description:
      "Sergio Vallín is the talented guitarist for Maná (which is Polynesian for positive energy), the most influential Spanish rock band worldwide, and one of the world's most popular bands regardless of language or genre. His new Gibson artist model has the features and performance he requires, including an ultra-light mahogany body with a two-piece plain maple top and a mahogany neck with a rosewood fretboard and '59 Rounded C profile. It also is equipped with Kluson® reissue tuners, a Bigsby® B7 vibrato, and features custom aging from the Murphy Lab, giving it the look and feel of a cherished vintage guitar. The electronics include a custom P-90 Soapbar pickup in the neck position and a bridge Custombucker, giving it excellent sonic versatility.",
    detail: {
      bodyStyle: "Les Paul",
      bodyShape: "Les Paul",
      bodyMaterial: "Mahogany",
      bodyFinish: "Murphy Lab Aged Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "Keb’ Mo’ “3.0” 12-Fret J-45",
    slug: "keb-mo-3.0-12-fret-j-45",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/24QpbXy6tQaOg1Jm0EMYPI/fe55b0e59925f2bd5e77eed834520185/AMRSKMVS_front_500x500.png?fit=fill&w=250&h=500",
      "https://images.ctfassets.net/m8onsx4mm13s/3s9his02lmIo4GZMP2e6dh/1e270adc083fec085a0abbed0564a90f/AMRSKMVS_back.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4af2JJunjfRBpWLiRG2Smv/736a91348a410e9c628119a0ec51031f/AMRSKMVS_beauty.png",
      "https://images.ctfassets.net/m8onsx4mm13s/7rJu81iWveAgY1dCgDuEQD/9ef209d1cdf390af997474ddbfea8413/AMRSKMVS_hs.png",
    ],
    highlight: false,
    price: 4299,
    stock: 30,
    category: "Acoustic",
    subtitle: "Artist Model 3.0 for Keb’ Mo’",
    description:
      "Gibson is proud to announce the third artist model made in collaboration with multi-talented guitarist, singer, songwriter, and five-time Grammy® award winner Keb’ Mo’ – the Keb’ Mo’ “3.0” 12-Fret J-45™. This new core model is ideal for a wide variety of musical compositions and playing styles and features a thermally aged Sitka spruce top, mahogany back and sides, and a 25” scale mahogany neck with a rosewood fretboard, custom Keb’ Mo’ profile, and open-back Grover® tuners. The neck joins the body at the 12th fret, giving this guitar the rounder, more full-bodied tone and exceptional playing comfort that only a 12-fret neck can provide. Equipped with L.R. Baggs electronics, it's studio and stage-ready, the moment you take it out of the included hardshell case.",
    detail: {
      bodyStyle: "Round Shoulder",
      bodyShape: "J-45",
      bodyMaterial: "Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "The Everly Brothers SJ-200",
    slug: "the-everly-brothers-sj-200",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/1mSDrJcp2mWEYd1tcQnGMF/d8c917258418751961e458d59ec3f342/DTCJBE2EB_front.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/3uRWp1oklgyhjFPSyUB0sz/213b91f390cf8cf4dee22eef65b3e994/DTCJBE2EB_back.png?h=900",
      "https://downloads.ctfassets.net/m8onsx4mm13s/5pqvSJM8ZWYSSbdxZeLUAk/5f013639ac33693fb12f6abbe8c76033/DTCJBE2EB_soundhole.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4TPlbIKPkxQ9yaP4Y5W81e/b9e37d677cc34527b2ed09b2b084573c/DTCJBE2EB_headstock.png?h=900",
    ],
    highlight: false,
    price: 7999,
    stock: 10,
    category: "Acoustic",
    subtitle: "A Tribute To One of Rock's Greatest Duos",
    description:
      "Phil and Don Everly were music royalty. Members of the Rock and Roll Hall of Fame, the Everly Brothers enjoyed a long string of highly influential hit records driven by their soaring harmonies and propelled by their matching Gibson acoustic guitars. The Gibson Acoustic Custom Shop is proud to celebrate their musical legacy with the release of The Everly Brothers SJ-200. Featuring AA flame maple back and sides paired with a thermally aged Sitka spruce top, which is capped with the dual pickguards that the Everly Brothers made famous. The Everly Brothers SJ-200 also has essential SJ-200 cosmetic features, such as the classic mother of pearl graduated crown inlays on the rosewood fretboard, as well as a Moustache™ bridge with four bar mother of pearl inlays. The bridge saddle, nut, and bri . . .",
    detail: {
      bodyStyle: "Super Jumbo",
      bodyShape: "SJ-200",
      bodyMaterial: "AA Flame Maple",
      bodyFinish: "Thin Finish Nitrocellulose",
    },
  },
  {
    brand: "Gibson",
    model: "Hummingbird Faded",
    slug: "hummingbird-faded",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/16RB13z7ZmTWndHpncfy2N/eca3cfc0546b5831bc018a6f24454f9b/OCSSHFAN_front.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/29JX6TD4Pfw4yyAkzzDRpW/b457777f285658a6e547e46d4eb1945c/OCSSHFAN_back.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4FVLyfWHSaFx4985lxCi08/e86d0927365c0f86b3610ead5bb2cb69/OCSSHFAN_beauty.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/2Qt3ef5qz74lJSxYn50Tny/3530966d12a6241d4237ee11f39790f8/OCSSHFAN_hs.png?h=900",
    ],
    highlight: false,
    price: 3499,
    stock: 20,
    category: "Acoustic",
    subtitle:
      "One of Gibson's Most Distinguished Acoustics, With a Beautiful Faded Finish",
    description:
      "The unmistakable Gibson Hummingbird™ is followed by the masses as one of the most remarkable acoustic guitars ever built. The new Hummingbird Faded blends vintage appointments and today's modern, high-quality build construction. The Hummingbird Faded is outfitted with gold Gotoh® Keystone tuners, a traditional Hummingbird truss rod cover, and a bone nut and saddle. The built-in LR Baggs VTC electronics make this guitar stage and studio-ready, right out of the included hardshell case.",
    detail: {
      bodyStyle: "Square Shoulder",
      bodyShape: "Hummingbird",
      bodyMaterial: "Mahogany",
      bodyFinish: "Satin Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "J-45 50s Faded",
    slug: "j-45-50s-faded",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/2oxQhASiSAdW2Hbo8fSojz/747da0393b444b1e6de0c275e16f135b/OCRS4FVS_front.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/1Gd8S4mJi5HrYhzS9kxJOb/e46857bdd6215b2b303816a3ab0f96bd/OCRS4FVS_back.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/23VuyXFVg4JJ0xIguol1Lp/2dc066c8412466e76d869572e443fbce/OCRS4FVS_beauty.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/2Qb06ErwU4KzxzPop8cOBq/6a9c6a8b6f51911bf30560492dbe94fe/OCRS4FVS_hs.png?h=900",
    ],
    highlight: false,
    price: 2499,
    stock: 40,
    category: "Acoustic",
    subtitle: "The World-Famous Workhorse With a Beautiful Faded Finish",
    description: `The J-45 is Gibson's best-selling acoustic of all time. Nicknamed "The Workhorse" and first introduced in 1942, this iconic acoustic has become the cornerstone of its round-shoulder, dreadnought line. World-renowned for its full, balanced expression, warm bass, and excellent projection, the J-45 has been refined to carry this legacy to new heights. The Gibson J-45 50s Faded delivers full-spectrum sound with incredible dynamic range, warm mids, and tight, punchy bass. Now available with a faded satin nitrocellulose lacquer finish that accentuates the guitar's vintage vibe and equipped with a modern LR Baggs pickup and electronics package for studio and stage use. A hardshell case is also included.`,
    detail: {
      bodyStyle: "Round Shoulder",
      bodyShape: "J-45",
      bodyMaterial: "Mahogany",
      bodyFinish: "Satin Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "Jerry Cantrell Atone Songwriter",
    slug: "jerry-cantrell-atone-songwriter",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/7pT5rswupHe0LpsO0eUJXL/3244cb6aca227791d66c6c290674c5ff/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_AMSSJCEB_front.jpg?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/7lUB0njMDSrf4j1959lLbS/b434ce9fc77c292e97a04ed49ecefdee/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_AMSSJCEB_back.jpg?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/6Ilms9pSy3EPqGhNWHRdNo/c673733d3df30825f9f38ec45e78727b/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_hardware-500_500.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4x6JQAl8kjXBrJ3fGQvngS/29126b76d33bc2aca1f9c50c977b1786/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_head-640_480.png?h=900",
    ],
    highlight: false,
    price: 3749,
    stock: 8,
    category: "Acoustic",
    subtitle:
      "An Ideal Blend of Modern and Traditional Features in an Artist Model Acoustic",
    description:
      "Whether you’re writing a song at home, laying it down in the studio, or bringing it to thousands on stage, the Jerry Cantrell “Atone” Songwriter delivers. Made to the Alice in Chains guitarist's specifications and prominently featured in his “Atone” video, the Jerry Cantrell “Atone” Songwriter builds upon the traditional Gibson Songwriter platform. It adds several unique, personalized features, including a thinner body depth for playing comfort, his signature “Circle in Square” pickguard, Jerry Cantrell signature on the truss rod cover, Double J waterslide decal on the back of the headstock, “12” inlay at the 12th fret, gold hardware with gold Grover® Mini Rotomatic® tuners, and an L.R. Baggs™ VTC pickup and preamp so it’s ready to plug in whenever you are.",
    detail: {
      bodyStyle: "Songwriter",
      bodyShape: "Songwriter",
      bodyMaterial: "Rosewood",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "Jerry Cantrell Atone Songwriter",
    slug: "jerry-cantrell-atone-songwriter",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/7pT5rswupHe0LpsO0eUJXL/3244cb6aca227791d66c6c290674c5ff/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_AMSSJCEB_front.jpg?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/7lUB0njMDSrf4j1959lLbS/b434ce9fc77c292e97a04ed49ecefdee/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_AMSSJCEB_back.jpg?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/6Ilms9pSy3EPqGhNWHRdNo/c673733d3df30825f9f38ec45e78727b/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_hardware-500_500.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4x6JQAl8kjXBrJ3fGQvngS/29126b76d33bc2aca1f9c50c977b1786/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_head-640_480.png?h=900",
    ],
    highlight: false,
    price: 3749,
    stock: 8,
    category: "Acoustic",
    subtitle:
      "An Ideal Blend of Modern and Traditional Features in an Artist Model Acoustic",
    description:
      "Whether you’re writing a song at home, laying it down in the studio, or bringing it to thousands on stage, the Jerry Cantrell “Atone” Songwriter delivers. Made to the Alice in Chains guitarist's specifications and prominently featured in his “Atone” video, the Jerry Cantrell “Atone” Songwriter builds upon the traditional Gibson Songwriter platform. It adds several unique, personalized features, including a thinner body depth for playing comfort, his signature “Circle in Square” pickguard, Jerry Cantrell signature on the truss rod cover, Double J waterslide decal on the back of the headstock, “12” inlay at the 12th fret, gold hardware with gold Grover® Mini Rotomatic® tuners, and an L.R. Baggs™ VTC pickup and preamp so it’s ready to plug in whenever you are.",
    detail: {
      bodyStyle: "Songwriter",
      bodyShape: "Songwriter",
      bodyMaterial: "Rosewood",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "SG Standard Bass",
    slug: "sg-standar-bass",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/1FwWFCcvYYSEtHVNrOPaq1/ce4170d25bc2ac00801efec5faba3331/__static.gibson.com_product-images_USA_USABCH291_Heritage_Cherry_BASG19HCCH1_front.jpg?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4N1L7RJsZpmVXUiSRJGHw7/b521910a86d5dde2af9498c23a3935ea/__static.gibson.com_product-images_USA_USABCH291_Heritage_Cherry_BASG19HCCH1_back.jpg?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/1X94lNgVGeyjVXkxiaNf88/9d4b4b1f7a3c5dcd6d595a37402e278c/__static.gibson.com_product-images_USA_USABCH291_Heritage_Cherry_hardware-500_500.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/1VGFwHV1MoweXZ120UZ66J/79abbfb9879b5095494ef0cfa622f378/__static.gibson.com_product-images_USA_USABCH291_Heritage_Cherry_neck-side-500_500.png?h=900",
    ],
    highlight: false,
    price: 1799,
    stock: 10,
    category: "Bass",
    subtitle: "Short Scale. Big Tone. Legendary Looks.",
    description:
      "The SG Bass has the legendary looks, sound and feel which made it one of Gibson's most iconic basses. The short scale length is actually a big part of this sound! While the short scale length of the SG Bass is preferred by smaller players, it's also preferred by many for the strong fundamental tone for which this short scale bass is known. As expected, the solid mahogany body has deeply sculpted scarfing and the rounded profile mahogany neck and rosewood fingerboard feels familiar and comfortable. A pair of calibrated SG bass pickups (neck and bridge) with individual volume and master tone controls add further tonal possibilities.",
    detail: {
      bodyStyle: "SG",
      bodyShape: "Bass",
      bodyMaterial: "Mahogany",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "Jerry Cantrell Atone Songwriter",
    slug: "jerry-cantrell-atone-songwriter",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/7pT5rswupHe0LpsO0eUJXL/3244cb6aca227791d66c6c290674c5ff/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_AMSSJCEB_front.jpg?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/7lUB0njMDSrf4j1959lLbS/b434ce9fc77c292e97a04ed49ecefdee/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_AMSSJCEB_back.jpg?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/6Ilms9pSy3EPqGhNWHRdNo/c673733d3df30825f9f38ec45e78727b/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_hardware-500_500.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4x6JQAl8kjXBrJ3fGQvngS/29126b76d33bc2aca1f9c50c977b1786/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_head-640_480.png?h=900",
    ],
    highlight: false,
    price: 3749,
    stock: 8,
    category: "Bass",
    subtitle:
      "An Ideal Blend of Modern and Traditional Features in an Artist Model Acoustic",
    description:
      "Whether you’re writing a song at home, laying it down in the studio, or bringing it to thousands on stage, the Jerry Cantrell “Atone” Songwriter delivers. Made to the Alice in Chains guitarist's specifications and prominently featured in his “Atone” video, the Jerry Cantrell “Atone” Songwriter builds upon the traditional Gibson Songwriter platform. It adds several unique, personalized features, including a thinner body depth for playing comfort, his signature “Circle in Square” pickguard, Jerry Cantrell signature on the truss rod cover, Double J waterslide decal on the back of the headstock, “12” inlay at the 12th fret, gold hardware with gold Grover® Mini Rotomatic® tuners, and an L.R. Baggs™ VTC pickup and preamp so it’s ready to plug in whenever you are.",
    detail: {
      bodyStyle: "Songwriter",
      bodyShape: "Songwriter",
      bodyMaterial: "Rosewood",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
  {
    brand: "Gibson",
    model: "Jerry Cantrell Atone Songwriter",
    slug: "jerry-cantrell-atone-songwriter",
    image: [
      "https://images.ctfassets.net/m8onsx4mm13s/7pT5rswupHe0LpsO0eUJXL/3244cb6aca227791d66c6c290674c5ff/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_AMSSJCEB_front.jpg?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/7lUB0njMDSrf4j1959lLbS/b434ce9fc77c292e97a04ed49ecefdee/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_AMSSJCEB_back.jpg?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/6Ilms9pSy3EPqGhNWHRdNo/c673733d3df30825f9f38ec45e78727b/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_hardware-500_500.png?h=900",
      "https://images.ctfassets.net/m8onsx4mm13s/4x6JQAl8kjXBrJ3fGQvngS/29126b76d33bc2aca1f9c50c977b1786/__static.gibson.com_product-images_Acoustic_ACC9WR562_Ebony_head-640_480.png?h=900",
    ],
    highlight: false,
    price: 3749,
    stock: 8,
    category: "Bass",
    subtitle:
      "An Ideal Blend of Modern and Traditional Features in an Artist Model Acoustic",
    description:
      "Whether you’re writing a song at home, laying it down in the studio, or bringing it to thousands on stage, the Jerry Cantrell “Atone” Songwriter delivers. Made to the Alice in Chains guitarist's specifications and prominently featured in his “Atone” video, the Jerry Cantrell “Atone” Songwriter builds upon the traditional Gibson Songwriter platform. It adds several unique, personalized features, including a thinner body depth for playing comfort, his signature “Circle in Square” pickguard, Jerry Cantrell signature on the truss rod cover, Double J waterslide decal on the back of the headstock, “12” inlay at the 12th fret, gold hardware with gold Grover® Mini Rotomatic® tuners, and an L.R. Baggs™ VTC pickup and preamp so it’s ready to plug in whenever you are.",
    detail: {
      bodyStyle: "Songwriter",
      bodyShape: "Songwriter",
      bodyMaterial: "Rosewood",
      bodyFinish: "Gloss Nitrocellulose Lacquer",
    },
  },
];

module.exports = products;
